<Workspace Version="1.3.4.6666" X="-172.032619670275" Y="99.7755743041739" zoom="1.48486197725882" ScaleFactor="1" Name="ElementRotate" Description="Rotates an element" ID="b6ddd6d0-ffb7-4195-a8fc-30679ad82646" Category="CIB.Revit.Elements.Element.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Elements.Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="4939ff1f-195d-4137-b395-e95bf4fb27ed" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('System')
from System.Collections.Generic import *

#Import the Revit Services
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

#Import the Revit Nodes
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

#Import the Revit API
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

#Import math functions
import math

#Define functions
def tolist(obj1):
	if hasattr(obj1,"__iter__"):
		return obj1
	else:
		return [obj1]
		
def FeetToMm(d):
	return float(d) * 304.8
	
def MmToFeet(d):
	return float(d) / 304.8
	
def Flatten(a, result=None):
	if result is None:
		result = []
	for x in a:
		if isinstance(x, list):
			Flatten(x, result)
		else:
			result.append(x)
	return result

#Define Input (IN)
element = UnwrapElement(IN[0])
degrees = math.radians(IN[1])

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

bbox = element.get_BoundingBox(doc.ActiveView)
midPoint = bbox.Min + ((bbox.Max - bbox.Min)/2)
axis = Line.CreateBound(midPoint, XYZ(midPoint.X, midPoint.Y, midPoint.Z+1000))
ElementTransformUtils.RotateElement(doc, element.Id, axis, degrees)

#End Transaction
TransactionManager.Instance.TransactionTaskDone()

#Define Output (OUT)
OUT = element
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fc7d78da-374e-4100-90e8-b287d06e25e8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-99.6363687019966" y="-18.7626928075188" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Element to Rotate&#xD;&#xA;element : Elements.Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5b850d31-9d5e-4e3b-b468-95b9b97c9061" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-45.9362479080634" y="122.826444899455" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Degrees &#xD;&#xA;degrees : double = 0" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a0f63b1a-d529-4c3e-99ca-dfeb8b061365" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="404.357730906248" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// Element &#xD;&#xA;element : Elements.Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4939ff1f-195d-4137-b395-e95bf4fb27ed" start_index="0" end="a0f63b1a-d529-4c3e-99ca-dfeb8b061365" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fc7d78da-374e-4100-90e8-b287d06e25e8" start_index="0" end="4939ff1f-195d-4137-b395-e95bf4fb27ed" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5b850d31-9d5e-4e3b-b468-95b9b97c9061" start_index="0" end="4939ff1f-195d-4137-b395-e95bf4fb27ed" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>