<Workspace Version="1.3.4.6666" X="60.218991181171" Y="-144.968787867084" zoom="0.87856213759097" ScaleFactor="1" Name="SubCategoryByName" Description="Checks if the given Family name exists in the current Document" ID="ae0b13ff-3707-449f-ad04-d00d351cf48a" Category="CIB.Revit.Elements.SubCategory.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="47c49c5a-e172-4498-8dd3-da4143c7c3da" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Name of the Subcategory" x="419.5" y="480" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Name of the Subcategory&#xD;&#xA;name :string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d1da4223-266c-4045-a8ba-22ca00a68eeb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="896.501480529616" y="497.578331123537" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// the Subcategory&#xD;&#xA;Subcategory : var" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e91ffd71-d53c-4a5b-874e-a4a08f5a0dda" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="The main Category" x="-26.5472014822179" y="565.741068705748" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The main Category to which the Subcategory belongs&#xD;&#xA;//In Family Document it will take the Category of the Family Document&#xD;&#xA;category:Category=null;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="63df2d6e-e826-4c93-a25b-f19a540e9dd5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="691.790577824549" y="508.750341885525" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System.Windows.Forms")
import System
from System.Windows.Forms import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#from System.Collections.Generic import *

#Utility functions
def tolist(obj1):
	if hasattr(obj1,"__iter__"):
		return obj1
	else:
		return [obj1]
		
def ContainsName(subCat, newName):
	bool = False
	for i in subCat:
		if newName == i.Name:
			bool = True
			break
		else:
			pass
	return bool


#The inputs to this node will be stored as a list in the IN variable.
newName = IN[0]

if doc.IsFamilyDocument:
	mainCategory = doc.OwnerFamily.FamilyCategory
else:
	mainCategory = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)

subCat = mainCategory.SubCategories
if mainCategory.CanAddSubcategory:
	
	if ContainsName(subCat, newName):
		subCategory = subCat[newName]
	else:
		newSubCategory = Categories.NewSubcategory(doc.Settings.Categories, mainCategory, newName)
		subCategory = newSubCategory
else:
	subCategory = subCat[newName]
	

TransactionManager.Instance.TransactionTaskDone()

OUT = subCategory</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="47c49c5a-e172-4498-8dd3-da4143c7c3da" start_index="0" end="63df2d6e-e826-4c93-a25b-f19a540e9dd5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e91ffd71-d53c-4a5b-874e-a4a08f5a0dda" start_index="0" end="63df2d6e-e826-4c93-a25b-f19a540e9dd5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="63df2d6e-e826-4c93-a25b-f19a540e9dd5" start_index="0" end="d1da4223-266c-4045-a8ba-22ca00a68eeb" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>