<Workspace Version="1.3.4.6666" X="509" Y="239" zoom="1" ScaleFactor="1" Name="ViewDuplicate" Description="Duplicates a given View" ID="5b6e6636-1102-40be-beae-1605b671a7b8" Category="CIB.Revit.Views.View.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Elements.View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="3e91b21c-6137-4d7b-ad54-3e54c0662d67" type="PythonNodeModels.PythonNode" nickname="Python Script | Duplicate View" x="251" y="-1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('System')
from System.Collections.Generic import *

#Import the Revit Services
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

#Import the Revit Nodes
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

#Import the Revit API
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

#Import math functions
import math

#Define functions
def tolist(obj1):
	if hasattr(obj1,"__iter__"):
		return obj1
	else:
		return [obj1]
		
def FeetToMm(d):
	return float(d) * 304.8
	
def MmToFeet(d):
	return float(d) / 304.8
	
def Flatten(a, result=None):
	if result is None:
		result = []
	for x in a:
		if isinstance(x, list):
			Flatten(x, result)
		else:
			result.append(x)
	return result
	
		
#Define Input (IN)
view = UnwrapElement(IN[0])
name = IN[1]
options = ViewDuplicateOption.Duplicate
output = None

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

try:
	elementId = view.Duplicate(options)
	dupliView = doc.GetElement(elementId)
	if name != None:
		UnwrapElement(dupliView).Name = name
	output = dupliView
except Exception as e:
	output = str(e)

#End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8cefdf33-8dd1-47b6-b04d-15cbcc47f7ef" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="-4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The View to Duplicate&#xD;&#xA;view : Elements.View" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ff6b6d70-cf55-4576-88ee-b07dfaa34134" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="526" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// Duplicated View&#xD;&#xA;view : Elements.View" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a8752ef5-ca38-4e2d-be89-8c95abdeee6d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-105" y="104" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The name of the duplicate View&#xD;&#xA;name : string = null;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3e91b21c-6137-4d7b-ad54-3e54c0662d67" start_index="0" end="ff6b6d70-cf55-4576-88ee-b07dfaa34134" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8cefdf33-8dd1-47b6-b04d-15cbcc47f7ef" start_index="0" end="3e91b21c-6137-4d7b-ad54-3e54c0662d67" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a8752ef5-ca38-4e2d-be89-8c95abdeee6d" start_index="0" end="3e91b21c-6137-4d7b-ad54-3e54c0662d67" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>