<Workspace Version="1.3.4.6666" X="290.761770850082" Y="267.624180959104" zoom="0.910063803931439" ScaleFactor="1" Name="ElementGetAnalyticalModel" Description="Returns the Analytical Model element of a given Element is this Element has one" ID="f426dbb2-e780-4432-a96e-b249f58ec17d" Category="CIB.Revit.Elements.Element.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Elements.Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="39a4a462-1dbf-4fc0-89fd-5cc6050d4ee6" type="PythonNodeModels.PythonNode" nickname="Python Script | Get Analytical model" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#Import the Revit Services
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

#Import the Revit Nodes
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#Import the Revit API
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import *

#Define tolist function
def tolist(obj1):
	if hasattr(obj1,"__iter__"):
		return obj1
	else:
		return [obj1]
		
#Define Input (IN)
element = UnwrapElement(IN[0])

if element.CanHaveAnalyticalModel():
	if element.GetAnalyticalModel() != None:
		output = element.GetAnalyticalModel()
	else:
		output = "Element doesn't have an Analytical Model"
else:
	output = "Element doesn't have an Analytical Model"


#End Transaction
TransactionManager.Instance.TransactionTaskDone()

#Define Output (OUT)
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ee3518cd-17f1-45a5-ac1e-81c4ca5afa3f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-118.860773597035" y="-6.72796831681333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Element&#xD;&#xA;element : Elements.Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="734465b6-b090-4350-b5af-4b3c7b4efeb0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="563" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// the Analytical Element of a String Error Message&#xD;&#xA;AnalyticalModelElement : var" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="39a4a462-1dbf-4fc0-89fd-5cc6050d4ee6" start_index="0" end="734465b6-b090-4350-b5af-4b3c7b4efeb0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ee3518cd-17f1-45a5-ac1e-81c4ca5afa3f" start_index="0" end="39a4a462-1dbf-4fc0-89fd-5cc6050d4ee6" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="2775.8017578125" eyeY="8370.5166015625" eyeZ="52939.859375" lookX="11915.373046875" lookY="-12908.3212890625" lookZ="-57590.97265625" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>