<Workspace Version="1.3.4.6666" X="-453.28097490625" Y="-316.403522009266" zoom="1.545620359375" ScaleFactor="1" Name="ViewDuplicateWithDetailing" Description="Duplicates a given View with all detailing elements" ID="89ca1830-ab74-47af-9dec-51898534663e" Category="CIB.Revit.Views.View.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Elements.View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="17e08679-8fb6-4f19-9fd5-a51b057e185b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="388" y="453" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The View to Duplicate&#xD;&#xA;view : var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8df77fff-05d4-475f-88ab-0dfb272466e1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="329" y="537" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The name of the duplicate View&#xD;&#xA;name : string = null;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="5a219b0b-e967-422b-8ad8-998a3fe0aeb2" type="PythonNodeModels.PythonNode" nickname="Python Script | Duplicate View" x="748" y="488" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('System')
from System.Collections.Generic import *

#Import the Revit Services
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

#Import the Revit Nodes
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

#Import the Revit API
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

#Import math functions
import math

#Define functions
def tolist(obj1):
	if hasattr(obj1,"__iter__"):
		return obj1
	else:
		return [obj1]
		
def FeetToMm(d):
	return float(d) * 304.8
	
def MmToFeet(d):
	return float(d) / 304.8
	
def Flatten(a, result=None):
	if result is None:
		result = []
	for x in a:
		if isinstance(x, list):
			Flatten(x, result)
		else:
			result.append(x)
	return result
	
		
#Define Input (IN)
view = UnwrapElement(IN[0])
name = IN[1]
options = ViewDuplicateOption.WithDetailing
output = None

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

try:
	elementId = view.Duplicate(options)
	dupliView = doc.GetElement(elementId)
	if name != None:
		UnwrapElement(dupliView).Name = name
	output = dupliView
except Exception as e:
	output = str(e)

#End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f2f248db-b30c-46c5-8034-2d351dd38635" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1023" y="489" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// Duplicated View&#xD;&#xA;view : Elements.View" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="17e08679-8fb6-4f19-9fd5-a51b057e185b" start_index="0" end="5a219b0b-e967-422b-8ad8-998a3fe0aeb2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8df77fff-05d4-475f-88ab-0dfb272466e1" start_index="0" end="5a219b0b-e967-422b-8ad8-998a3fe0aeb2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a219b0b-e967-422b-8ad8-998a3fe0aeb2" start_index="0" end="f2f248db-b30c-46c5-8034-2d351dd38635" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>